language: java
script:
  - cd unit_pathfinder_tira
  - ./gradlew check
  - ./gradlew jacocoTestReport
test:
  post:
      - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
      - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
after_success:
  - bash <(curl -s https://codecov.io/bash)