language: java
jdk:
  - oraclejdk8
before_script:
  - chmod +x unit_pathfinder_tira/gradlew
script:
  - unit_pathfinder_tira/gradlew check
  - unit_pathfinder_tira/gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
